version: '2.1'
services:
  oauth:
    build: 
        context: .
        dockerfile: oauth.dockerfile
    ports:
      - "5001:5001" 
    networks:
      default:

networks:
  default:
    external:
      name: nat