version: '2.1'
services:
  oauth:
    build: 
        context: .
        dockerfile: oauth.dockerfile
    ports:
      - "5001:5001" 

  web:
    build:
       context: .
       dockerfile: web.dockerfile

    ports:
      - "5000:5000"  
    links: 
      - oauth

networks:
  default:
    external:
      name: nat